WhlTeam.create!([
  { name: 'Spokane Chiefs', hockeytech_id: '215', city: 'Spokane', team_name: 'Chiefs', conference: 'Western', division: 'U.S. Division' },
  { name: 'Seattle Thunderbirds', hockeytech_id: '214', city: 'Seattle', team_name: 'Thunderbirds', conference: 'Western', division: 'U.S. Division' },
  { name: 'Kelowna Rockets', hockeytech_id: '204', city: 'Kelowna', team_name: 'Rockets', conference: 'Western', division: 'B.C. Division' },
  { name: 'Penticton Vees', hockeytech_id: '277', city: 'Penticton', team_name: 'Vees', conference: 'Western', division: 'B.C. Division' },
  { name: 'Portland Winterhawks', hockeytech_id: '208', city: 'Portland', team_name: 'Winterhawks', conference: 'Western', division: 'U.S. Division' },
  { name: 'Everett Silvertips', hockeytech_id: '226', city: 'Everett', team_name: 'Silvertips', conference: 'Western', division: 'U.S. Division' },
  { name: 'Tri-City Americans', hockeytech_id: '217', city: 'Tri-City', team_name: 'Americans', conference: 'Western', division: 'U.S. Division' },
  { name: 'Kamloops Blazers', hockeytech_id: '203', city: 'Kamloops', team_name: 'Blazers', conference: 'Western', division: 'B.C. Division' },
  { name: 'Prince George Cougars', hockeytech_id: '210', city: 'Prince George', team_name: 'Cougars', conference: 'Western', division: 'B.C. Division' },
  { name: 'Vancouver Giants', hockeytech_id: '223', city: 'Vancouver', team_name: 'Giants', conference: 'Western', division: 'B.C. Division' },
  { name: 'Victoria Royals', hockeytech_id: '227', city: 'Victoria', team_name: 'Royals', conference: 'Western', division: 'B.C. Division' },
  { name: 'Brandon Wheat Kings', hockeytech_id: '201', city: 'Brandon', team_name: 'Wheat Kings', conference: 'Eastern', division: 'East Division' },
  { name: 'Swift Current Broncos', hockeytech_id: '216', city: 'Swift Current', team_name: 'Broncos', conference: 'Eastern', division: 'East Division' },
  { name: 'Medicine Hat Tigers', hockeytech_id: '206', city: 'Medicine Hat', team_name: 'Tigers', conference: 'Eastern', division: 'East Division' },
  { name: 'Edmonton Oil Kings', hockeytech_id: '228', city: 'Edmonton', team_name: 'Oil Kings', conference: 'Western', division: 'Central Division' },
  { name: 'Moose Jaw Warriors', hockeytech_id: '207', city: 'Moose Jaw', team_name: 'Warriors', conference: 'Eastern', division: 'East Division' },
  { name: 'Regina Pats', hockeytech_id: '212', city: 'Regina', team_name: 'Pats', conference: 'Eastern', division: 'East Division' },
  { name: 'Saskatoon Blades', hockeytech_id: '213', city: 'Saskatoon', team_name: 'Blades', conference: 'Eastern', division: 'East Division' },
  { name: 'Prince Albert Raiders', hockeytech_id: '209', city: 'Prince Albert', team_name: 'Raiders', conference: 'Eastern', division: 'East Division' },
  { name: 'Calgary Hitmen', hockeytech_id: '202', city: 'Calgary', team_name: 'Hitmen', conference: 'Western', division: 'Central Division' },
  { name: 'Lethbridge Hurricanes', hockeytech_id: '205', city: 'Lethbridge', team_name: 'Hurricanes', conference: 'Western', division: 'Central Division' },
  { name: 'Red Deer Rebels', hockeytech_id: '211', city: 'Red Deer', team_name: 'Rebels', conference: 'Western', division: 'Central Division' },
  { name: 'Wenatchee Wild', hockeytech_id: '222', city: 'Wenatchee', team_name: 'Wild', conference: 'Western', division: 'U.S. Division' }
])
